<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net47;net48;net8.0-windows</TargetFrameworks>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <!-- RevitVersion -->
  <Choose>
    <When Condition="$(TargetFramework.StartsWith('net47'))">
      <PropertyGroup>
        <RevitVersion>2019</RevitVersion>
      </PropertyGroup>
    </When>
    <When Condition="$(TargetFramework.StartsWith('net48'))">
      <PropertyGroup>
        <RevitVersion>2024</RevitVersion>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <RevitVersion>2025</RevitVersion>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  
  <!-- Net Core -->
  <PropertyGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <!-- Release -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\$(RevitVersion)</OutputPath>
    <DefineConstants>$(DefineConstants);REVIT$(RevitVersion)</DefineConstants>
    <NoWarn>MSB3052</NoWarn>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <!-- Debug -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug\$(RevitVersion)</OutputPath>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;REVIT$(RevitVersion)</DefineConstants>
    <DebugType>Full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="RevitTest.cs" />
    <None Include="Utils\OneTimeOpenDocumentTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="ricaun.RevitTest.TestAdapter" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" Condition="!$(TargetFramework.StartsWith('net4'))" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*" IncludeAssets="build; compile" PrivateAssets="All" />
  </ItemGroup>

  <!-- Release -->
  <ItemGroup Condition="!$(Configuration.Contains('Debug'))">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Open</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Close</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ricaun.Revit.ExtensibleJson\ricaun.Revit.ExtensibleJson.csproj" />
  </ItemGroup>

</Project>